### PR TITLE
Create LICENSE

### LINKED ISSUE #8: Add LICENSE

### PR DESCRIPTION
**Pull request by fm75**
Fixes #8

### CODE REVIEW

**Comment by jzf2101** [comment]
@JamiesHQ can you confirm no changes are allowed?

**Comment by JamiesHQ** [comment]
@Carreau please confirm @jzf2101's note above

**Comment by takluyver** [comment]
I think if we do change anything it should be on the `gh-pages` branch, not master (I've just edited the settings on Github to make gh-pages the default branch).

But I'm not convinced that we need to change anything: this repo exists to serve built docs for older versions of IPython, and those docs already include the license information:
http://ipython.org/ipython-doc/3/about/license_and_copyright.html

**Comment by Carreau** [comment]
The only case where we do changes is when things break in old docs, or when an old make is too much referenced by google in which case we set the canonical link to RTFD. Sorry about the confusion. Closing. I'll see if I also can deactivate issues ont this repo.

**Pull request closed without merging**
