### PR TITLE
Inject rel=canonical in ipython 2 and 3 docs

### PR DESCRIPTION
**Pull request by Carreau**
Do that only when the new page exists (ie status == 200)

---

Hopefully that can start to move some of google referencing of old version of IPython's doc out of the way. 

I was unsure whether to use stable or latest so I copied what readthedocs is doing. Everything point to stable.

### CODE REVIEW

**Comment by Carreau** [comment]
One of the things I can do is to link to `index.html` if the new page does not exists. Thoughts ?

Maybe @willingc , @takluyver ? @rgbkrk you're an SEO expert aren't you ?

**Comment by minrk** [comment]
Is there a script doing the checking? How are you generating the links and checking their targets?

**Comment by minrk** [comment]
The only reason to not do index.html if the link target doesn't resolve I think is because there are multiple target repos now, and there's a good likelihood that the failure to resolve is due to pointing to the wrong repo, not that there is no good candidate.

**Comment by willingc** [comment]
I'm not sure that I fully understand what we are trying to accomplish here. There is some RTD support for canonical links: http://docs.readthedocs.io/en/latest/canonical.html

**Comment by minrk** [comment]
@willingc this is adding canonical links to the _old_ IPython docs, pointing to the new ones on RTD. The aim is largely to address the fact that the old docs still rank above the new ones on search engines quite often, and Google takes canonical links into account in search results.

**Comment by willingc** [comment]
Thanks @minrk. I just realized that I didn't even know this repo existed. Let me make sure that I understand what IPython docs are doing and where:
- This repo, `gh-pages` branch: hosts all of the old IPython docs on GitHub using the ipython.org   domain (such as http://ipython.org/ipython-doc/3/index.html)
- ReadTheDocs currently set to display `stable` as default: source for the docs are found in the ipython/ipython repo. (FYI - I don't have admin access to the IPython on RTD so I don't know the config settings).

What we are trying to do is to make sure that the old docs resolve to the new page if there is one. If the old doc page doesn't have an equivalent new page, then ???

**Comment by minrk** [comment]
@willingc yup, this is where docs used to be before we moved to RTD. What to do when we don't find a place to redirect to is the missing bit. This PR ignores those for now, and just adds links for the ones with known targets.

I added you to the IPython repo on RTD.

**Comment by willingc** [comment]
@minrk Thanks. Got it. Perhaps we can map out the pages (not sure how many we are talking about) that don't link to new docs and determine the best place for them to redirect. I could imagine some would go to new ipython and some to jupyter docs.

**Comment by willingc** [comment]
This PR seems reasonable to merge and then open a new issue to cover the other pages with no new page. Thoughts?

**Comment by minrk** [comment]
@willingc yup!

**Comment by willingc** [comment]
Thanks @Carreau :cake:

**Comment by rgbkrk** [comment]
Great!

**Comment by Carreau** [comment]
> Is there a script doing the checking? How are you generating the links and checking their targets?

a rough notebook that I can cleanup. I had no intension to as it is a once only pass. 

```
def treatfile(lines, path):
    """ lines comes from fp.readlines(), version is the current version I'm fixing. path is path to file relative to the /<version>/ folder. 
    """
    for l in lines:
        if '</head>' not in l:
            yield l
        else:
            root = 'http://ipython.readthedocs.io/en/stable'
            newurl = '{root}/{path}'.format(root=root, path=path)
            code = requests.get(newurl).status_code
            if code == 200:
                new = l.replace(
                     '</head>',
                     '   <link rel="canonical" href="{nurl}"/>\n</head>'.
                     format(nurl=newurl)

                )
                yield new
            else:
                yield l
```

**Comment by minrk** [comment]
Thanks, I was just curious. A lot of the old docs pages are now in non-ipython docs (e.g. messaging). Do you want to take a stab at any of those, or not worth it?

**Pull request merged**
